window.DEALER_CONFIG = {
  dealer: {
    name: 'DK AUTO',
    shortName: 'DK',
    tagline: 'Автомобили с пробегом',
    city: 'Москва',
    address: 'ул. Автомобильная, 10',
    phone: '+7 (961) 924-57-10',
    phoneLink: '+79619245710',
    messenger: 'https://t.me/dk_auto_demo',
    hours: 'Ежедневно, 9:00–20:00',
    experience: '8 лет',
    sold: '850+'
  },
  cars: [
    {
      id: 'geely-monjaro',
      brand: 'Geely',
      model: 'Monjaro',
      year: 2024,
      price: 3296000,
      mileage: 11400,
      engine: '2,0 л · 238 л.с.',
      transmission: 'Автомат',
      drive: 'Полный',
      body: 'Кроссовер',
      color: 'Серый металлик',
      owners: '1 владелец',
      status: 'В наличии',
      cardImage: 'assets/geely-monjaro.png',
      images: ['assets/listings/geely-monjaro-1.jpg', 'assets/listings/geely-monjaro-2.jpg', 'assets/listings/geely-monjaro-3.jpg'],
      description: 'Богатая комплектация, полный привод, панорамная крыша и камеры 360°. Автомобиль проверен и готов к осмотру.'
    },
    {
      id: 'kia-k3',
      brand: 'Kia',
      model: 'The New K3',
      year: 2024,
      price: 1897000,
      mileage: 33119,
      engine: '1,6 л · 123 л.с.',
      transmission: 'Автомат',
      drive: 'Передний',
      body: 'Седан',
      color: 'Белый',
      owners: '1 владелец',
      status: 'Хорошая цена',
      images: ['assets/listings/kia-k3-1.webp', 'assets/listings/kia-k3-2.webp', 'assets/listings/kia-k3-3.webp'],
      description: 'Экономичный городской седан. Чистый салон, подтвержденный пробег, климат-контроль и камера заднего вида.'
    },
    {
      id: 'hyundai-avante',
      brand: 'Hyundai',
      model: 'The New Avante',
      year: 2024,
      price: 1950000,
      mileage: 11063,
      engine: '1,6 л · 123 л.с.',
      transmission: 'Автомат',
      drive: 'Передний',
      body: 'Седан',
      color: 'Серый',
      owners: '1 владелец',
      status: 'Малый пробег',
      images: ['assets/listings/hyundai-avante-1.webp', 'assets/listings/hyundai-avante-2.webp', 'assets/listings/hyundai-avante-3.webp'],
      description: 'Современный седан с минимальным пробегом. Полностью обслужен, без вложений после покупки.'
    },
    {
      id: 'changan-cs35',
      brand: 'Changan',
      model: 'CS35 Plus',
      year: 2024,
      price: 2427000,
      mileage: 13400,
      engine: '1,4 л · 150 л.с.',
      transmission: 'Робот',
      drive: 'Передний',
      body: 'Кроссовер',
      color: 'Серый',
      owners: '1 владелец',
      status: 'В наличии',
      images: ['assets/listings/changan-cs35-1.jpg', 'assets/listings/changan-cs35-2.jpg', 'assets/listings/changan-cs35-3.jpg'],
      description: 'Компактный кроссовер с турбомотором, мультимедиа, зимним пакетом и заводской гарантией.'
    },
    {
      id: 'kia-sorento',
      brand: 'Kia',
      model: 'Sorento',
      year: 2023,
      price: 3650000,
      mileage: 48700,
      engine: '2,2 л · 199 л.с.',
      transmission: 'Робот',
      drive: 'Полный',
      body: 'Кроссовер',
      color: 'Черный',
      owners: '1 владелец',
      status: 'Семейный',
      cardImage: 'assets/kia-sorento-2026.png',
      images: ['assets/kia-sorento-2026.png'],
      description: 'Просторный семиместный кроссовер. Дизель, полный привод, кожаный салон и полный комплект документов.'
    },
    {
      id: 'genesis-gv70',
      brand: 'Genesis',
      model: 'GV70',
      year: 2023,
      price: 4900000,
      mileage: 28600,
      engine: '2,5 л · 304 л.с.',
      transmission: 'Автомат',
      drive: 'Полный',
      body: 'Кроссовер',
      color: 'Белый',
      owners: '1 владелец',
      status: 'Премиум',
      cardImage: 'assets/genesis-gv70-2027.webp',
      images: ['assets/genesis-gv70-2027.webp'],
      description: 'Премиальный кроссовер с полным приводом, ассистентами водителя, премиальной акустикой и панорамой.'
    },
    {
      id: 'chery-tiggo',
      brand: 'Chery',
      model: 'Tiggo 7 Pro Max',
      year: 2024,
      price: 2760000,
      mileage: 9600,
      engine: '1,6 л · 150 л.с.',
      transmission: 'Робот',
      drive: 'Полный',
      body: 'Кроссовер',
      color: 'Серый',
      owners: '1 владелец',
      status: 'На гарантии',
      cardImage: 'assets/chery-tiggo7-pro-max.png',
      images: ['assets/chery-tiggo7-pro-max.png'],
      description: 'Полноприводная версия в максимальной комплектации. Заводская гарантия и комплект зимних шин.'
    },
    {
      id: 'omoda-c5',
      brand: 'Omoda',
      model: 'C5',
      year: 2023,
      price: 2350000,
      mileage: 22100,
      engine: '1,5 л · 147 л.с.',
      transmission: 'Вариатор',
      drive: 'Передний',
      body: 'Кроссовер',
      color: 'Белый',
      owners: '1 владелец',
      status: 'В наличии',
      cardImage: 'assets/omoda-c5.png',
      images: ['assets/omoda-c5.png'],
      description: 'Яркий городской кроссовер с цифровой панелью, камерами кругового обзора и подогревами.'
    }
  ]
};
